import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    dashboard: 'Dashboard',
    clients: 'Clients',
    packages: 'Packages',
    bookings: 'Bookings',
    invoices: 'Invoices',
    reports: 'Reports',
    expenses: 'Expenses',
    settings: 'Settings',
    logout: 'Logout',
    search: 'Search...',
    add_new: 'Add New',
    total_revenue: 'Total Revenue',
    currency: 'EGP',
    outstanding: 'Outstanding',
    active_sessions: 'Active Sessions',
    save_changes: 'Save Changes',
    language: 'Language',
    arabic: 'Arabic',
    english: 'English',
    studio_name: 'Studio Name',
    studio_email: 'Studio Email',
    appearance: 'Appearance',
    dark_mode: 'Dark Mode',
    accent_color: 'Brand Color',
    logo: 'Studio Logo',
    click_to_upload: 'Click to upload logo',
    welcome_back: 'Welcome back',
    overview: 'Overview',
    overview_subtitle: 'Welcome back to Studio Business Management.',
    new_booking: 'New Booking',
    total_clients: 'Total Clients',
    total_bookings: 'Total Bookings',
    pending_invoices: 'Pending Invoices',
    revenue_stats: 'Revenue Statistics',
    upcoming_events: 'Upcoming Events',
    view_all: 'View All',
    no_events: 'No upcoming events scheduled.',
    id: 'ID',
    client: 'Client',
    amount: 'Amount',
    paid: 'Paid',
    due_date: 'Due Date',
    status: 'Status',
    actions: 'Actions',
    item_description: 'Item Description',
    price: 'Price',
    quantity: 'Quantity',
    total: 'Total',
    total_amount: 'Total Amount',
    paid_amount: 'Paid Amount',
    balance_due: 'Balance Due',
    thank_you: 'Thank you for your business!',
    // Clients
    clients_title: 'Clients',
    clients_subtitle: 'Manage your client relationships and contact details.',
    client_name: 'Client Name',
    phone: 'Phone',
    email: 'Email',
    add_client: 'Add Client',
    new_client: 'New Client',
    edit_client: 'Edit Client',
    full_name: 'Full Name',
    save_client: 'Save Client',
    // Packages
    packages_title: 'Service Packages',
    packages_subtitle: 'Define your photography services and pricing.',
    package_name: 'Package Name',
    description: 'Description',
    duration: 'Duration (Min)',
    add_package: 'Add Package',
    new_package: 'New Package',
    edit_package: 'Edit Package',
    sessions: 'Sessions',
    albums: 'Albums',
    prints: 'Prints',
    no_packages: 'No packages defined yet.',
    // Bookings
    bookings_title: 'Bookings',
    bookings_subtitle: 'Schedule and manage your upcoming sessions.',
    event_date: 'Event Date',
    select_client: 'Select Client',
    select_package: 'Select Package',
    booking_status: 'Booking Status',
    add_booking: 'Add Booking',
    all_sessions: 'All Sessions',
    quick_stats: 'Quick Stats',
    confirm_booking: 'Confirm Booking',
    select_booking_placeholder: 'Choose a booking...',
    select_client_placeholder: 'Choose a client...',
    select_package_placeholder: 'Choose a package...',
    calendar_view: 'Calendar View',
    list_view: 'List View',
    next_month: 'Next Month',
    prev_month: 'Previous Month',
    sun: 'Sun', mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat',
    // Invoices
    invoices_title: 'Invoices',
    invoices_subtitle: 'Track billing, payments, and late invoices.',
    create_invoice: 'Create Invoice',
    invoice_number: 'Invoice Number',
    select_booking: 'Select Booking',
    paid_status: 'Paid',
    partially_paid_status: 'Partially Paid',
    unpaid_status: 'Unpaid',
    overdue: 'Overdue',
    // Reports
    reports_title: 'Financial Reports',
    reports_subtitle: 'Advanced analytics and performance tracking.',
    export_csv: 'Export CSV',
    generate_pdf: 'Generate PDF',
    revenue_by_category: 'Revenue by Category',
    package_popularity: 'Package Popularity',
    total_revenue_paid: 'Total Revenue (Paid)',
    outstanding_dues: 'Outstanding Dues',
    total_sessions: 'Total Sessions',
    financial_summary: 'Financial Summary',
    metric: 'Metric',
    value: 'Value',
    package_type: 'Package Type',
    count: 'Count',
    csv_export_success: 'CSV Exported Successfully!',
    pdf_export_success: 'PDF Generated Successfully!',
    pdf_export_error: 'Error generating PDF. Check console.',
    realtime_badge: '+Realtime',
    // Settings Items
    studio_identity: 'Studio Identity',
    studio_email_label: 'Studio Email (for Invoices)',
    brand_color: 'Brand Accent Color',
    remove_logo: 'Remove Logo',
    save_success: 'Settings saved successfully!',
    // Statuses
    lead: 'Lead',
    booked: 'Booked',
    confirmed: 'Confirmed',
    completed: 'Completed',
    cancelled: 'Cancelled',
    all_statuses: 'All Statuses',
    // Toasts
    client_added: 'Client added successfully!',
    client_updated: 'Client updated!',
    client_deleted: 'Client deleted.',
    package_created: 'Package created!',
    package_updated: 'Package updated!',
    package_deleted: 'Package removed.',
    booking_created: 'Booking confirmed!',
    booking_updated: 'Booking updated!',
    booking_deleted: 'Booking cancelled.',
    invoice_generated: 'Invoice generated!',
    invoice_deleted: 'Invoice record removed.',
    pdf_generating: 'Generating PDF, please wait...',
    download_started: 'Download started!',
    export_failed: 'Export failed!',
    settings_saved: 'Settings saved successfully!',
    logo_changed: 'Studio logo updated.',
    // General
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete_confirm_title: 'Are you sure?',
    delete_confirm_msg: 'This action cannot be undone.',
    loading: 'Loading...',
    no_options: 'No options available',
    change_logo: 'Change Logo',
    settings_subtitle: 'Manage your studio preferences.',
    edit: 'Edit',
    delete: 'Delete',
    // Expenses
    expenses_title: 'Expenses',
    expenses_subtitle: 'Track your studio outgoings and operational costs.',
    add_expense: 'Add Expense',
    new_expense: 'New Expense',
    edit_expense: 'Edit Expense',
    expense_description: 'Expense Description',
    expense_category: 'Category',
    expense_date: 'Date',
    total_expenses: 'Total Expenses',
    net_profit: 'Net Profit',
    cat_rent: 'Rent',
    cat_equipment: 'Equipment',
    cat_marketing: 'Marketing',
    cat_software: 'Software',
    cat_others: 'Others',
    expense_added: 'Expense recorded!',
    expense_updated: 'Expense updated!',
    expense_deleted: 'Expense removed.'
  },
  ar: {
    dashboard: 'لوحة التحكم',
    clients: 'العملاء',
    packages: 'الباقات',
    bookings: 'الحجوزات',
    invoices: 'الفواتير',
    reports: 'التقارير',
    expenses: 'المصروفات',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    search: 'بحث...',
    add_new: 'إضافة جديد',
    total_revenue: 'إجمالي الإيرادات',
    currency: 'ج.م',
    outstanding: 'المبالغ المستحقة',
    active_sessions: 'الجلسات النشطة',
    save_changes: 'حفظ التغييرات',
    language: 'اللغة',
    arabic: 'العربية',
    english: 'الإنجليزية',
    studio_name: 'اسم الاستوديو',
    studio_email: 'البريد الإلكتروني',
    appearance: 'المظهر',
    dark_mode: 'الوضع الليلي',
    accent_color: 'لون العلامة التجارية',
    logo: 'شعار الاستوديو',
    click_to_upload: 'اضغط لرفع الشعار',
    welcome_back: 'مرحباً بك',
    overview: 'نظرة عامة',
    overview_subtitle: 'مرحباً بك مرة أخرى في إدارة استوديو الأعمال.',
    new_booking: 'حجز جديد',
    total_clients: 'إجمالي العملاء',
    total_bookings: 'إجمالي الحجوزات',
    pending_invoices: 'فواتير معلقة',
    revenue_stats: 'إحصائيات الإيرادات',
    upcoming_events: 'الفعاليات القادمة',
    view_all: 'عرض الكل',
    no_events: 'لا توجد فعاليات قادمة مجدولة.',
    id: 'المعرف',
    client: 'العميل',
    amount: 'المبلغ',
    paid: 'المدفوع',
    due_date: 'تاريخ الاستحقاق',
    status: 'الحالة',
    actions: 'الإجراءات',
    item_description: 'وصف العنصر',
    price: 'السعر',
    quantity: 'الكمية',
    total: 'المجموع',
    total_amount: 'المبلغ الإجمالي',
    paid_amount: 'المبلغ المدفوع',
    balance_due: 'الرصيد المتبقي',
    thank_you: 'شكراً لتعاملك معنا!',
    // Clients
    clients_title: 'العملاء',
    clients_subtitle: 'إدارة علاقات العملاء وتفاصيل الاتصال.',
    client_name: 'اسم العميل',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    add_client: 'إضافة عميل',
    new_client: 'عميل جديد',
    edit_client: 'تعديل بيانات العميل',
    full_name: 'الاسم بالكامل',
    save_client: 'حفظ العميل',
    // Packages
    packages_title: 'باقات الخدمات',
    packages_subtitle: 'تحديد خدمات التصوير والأسعار.',
    package_name: 'اسم الباقة',
    description: 'الوصف',
    duration: 'المدة (بالدقائق)',
    add_package: 'إضافة باقة',
    new_package: 'باقة جديدة',
    edit_package: 'تعديل الباقة',
    sessions: 'جلسات',
    albums: 'ألبومات',
    prints: 'مطبوعات',
    no_packages: 'لم يتم تعريف أي باقات بعد.',
    // Bookings
    bookings_title: 'الحجوزات',
    bookings_subtitle: 'جدولة وإدارة جلساتك القادمة.',
    event_date: 'تاريخ الفعالية',
    select_client: 'اختر العميل',
    select_package: 'اختر الباقة',
    booking_status: 'حالة الحجز',
    add_booking: 'إضافة حجز',
    all_sessions: 'جميع الجلسات',
    quick_stats: 'إحصائيات سريعة',
    confirm_booking: 'تأكيد الحجز',
    select_booking_placeholder: 'اختر الحجز...',
    select_client_placeholder: 'اختر العميل...',
    select_package_placeholder: 'اختر الباقة...',
    calendar_view: 'عرض التقويم',
    list_view: 'عرض القائمة',
    next_month: 'الشهر التالي',
    prev_month: 'الشهر السابق',
    sun: 'أحد', mon: 'اثنين', tue: 'ثلاثاء', wed: 'أربعاء', thu: 'خميس', fri: 'جمعة', sat: 'سبت',
    // Invoices
    invoices_title: 'الفواتير',
    invoices_subtitle: 'تتبع الفواتير والمدفوعات والمستحقات المتاخرة.',
    create_invoice: 'إنشاء فاتورة',
    invoice_number: 'رقم الفاتورة',
    select_booking: 'اختر الحجز',
    paid_status: 'مدفوع',
    partially_paid_status: 'مدفوع جزئياً',
    unpaid_status: 'غير مدفوع',
    overdue: 'متأخر',
    // Reports
    reports_title: 'التقارير المالية',
    reports_subtitle: 'تحليلات متقدمة وتتبع الأداء.',
    export_csv: 'تصدير CSV',
    generate_pdf: 'إنشاء PDF',
    revenue_by_category: 'الإيرادات حسب الفئة',
    package_popularity: 'شعبية الباقات',
    total_revenue_paid: 'إجمالي الإيرادات (المدفوعة)',
    outstanding_dues: 'المستحقات القائمة',
    total_sessions: 'إجمالي الجلسات',
    financial_summary: 'ملخص مالي',
    metric: 'المقياس',
    value: 'القيمة',
    package_type: 'نوع الباقة',
    count: 'العدد',
    csv_export_success: 'تم تصدير CSV بنجاح!',
    pdf_export_success: 'تم إنشاء PDF بنجاح!',
    pdf_export_error: 'خطأ في إنشاء PDF. تحقق من الكونسول.',
    realtime_badge: '+مباشر',
    // Settings Items
    studio_identity: 'هوية الاستوديو',
    studio_email_label: 'البريد الإلكتروني للاستوديو (للفواتير)',
    brand_color: 'لون العلامة التجارية',
    remove_logo: 'إزالة الشعار',
    save_success: 'تم حفظ الإعدادات بنجاح!',
    // Statuses
    lead: 'مهتم',
    booked: 'محجوز',
    confirmed: 'مؤكد',
    completed: 'مكتمل',
    cancelled: 'ملغى',
    all_statuses: 'جميع الحالات',
    // Toasts
    client_added: 'تم إضافة العميل بنجاح!',
    client_updated: 'تم تحديث بيانات العميل!',
    client_deleted: 'تم حذف العميل.',
    package_created: 'تم إنشاء الباقة بنجاح!',
    package_updated: 'تم تحديث الباقة!',
    package_deleted: 'تم حذف الباقة.',
    booking_created: 'تم تأكيد الحجز!',
    booking_updated: 'تم تحديث الحجز!',
    booking_deleted: 'تم إلغاء الحجز.',
    invoice_generated: 'تم إنشاء الفاتورة!',
    invoice_deleted: 'تم حذف سجل الفاتورة.',
    pdf_generating: 'جاري إنشاء ملف PDF، يرجى الانتظار...',
    download_started: 'بدأ التحميل!',
    export_failed: 'فشل التصدير!',
    settings_saved: 'تم حفظ الإعدادات بنجاح!',
    logo_changed: 'تم تحديث شعار الاستوديو.',
    // General
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    delete_confirm_title: 'هل أنت متأكد؟',
    delete_confirm_msg: 'لا يمكن التراجع عن هذا الإجراء.',
    loading: 'جاري التحميل...',
    no_options: 'لا توجد خيارات متاحة',
    change_logo: 'تغيير الشعار',
    settings_subtitle: 'إدارة تفضيلات الاستوديو الخاص بك.',
    edit: 'تعديل',
    delete: 'حذف',
    // Expenses
    expenses_title: 'المصروفات',
    expenses_subtitle: 'تتبع مدفوعات الاستوديو والتكاليف التشغيلية.',
    add_expense: 'إضافة مصروف',
    new_expense: 'مصروف جديد',
    edit_expense: 'تعديل المصروف',
    expense_description: 'وصف المصروف',
    expense_category: 'الفئة',
    expense_date: 'التاريخ',
    total_expenses: 'إجمالي المصروفات',
    net_profit: 'صافي الربح',
    cat_rent: 'إيجار',
    cat_equipment: 'معدات',
    cat_marketing: 'تسويق',
    cat_software: 'برامج',
    cat_others: 'أخرى',
    expense_added: 'تم تسجيل المصروف!',
    expense_updated: 'تم تحديث المصروف!',
    expense_deleted: 'تم حذف المصروف.'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('language') || 'en');

  useEffect(() => {
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    if (lang === 'ar') {
      document.body.classList.add('rtl');
    } else {
      document.body.classList.remove('rtl');
    }
  }, [lang]);

  const t = (key) => {
    if (!translations[lang]) return key;
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => useContext(LanguageContext);
